Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.stage}-notes
      AttributeDefinitions:
        - AttributeName: accountID
          AttributeType: S
        - AttributeName: noteID
          AttributeType: S
      KeySchema:
        - AttributeName: accountID
          KeyType: HASH
        - AttributeName: noteID
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
